version: "2.0"

services: 
  my-app:
    image: nidhey27/repo-pattern-user-rest-api
    environment: 
      - DB_HOST=mysql-db
      - DB_NAME=dapi_assg_db
      - DB_USER=dan
      - DB_PASSWORD=secret
      - DB_PORT=3306
    ports:
      - "8080:8080"
    container_name: my-app

    



